### ISSUE TITLE
Installation via npm

### ISSUE THREAD

**Issue by MartyIX** [garakh/ngSilent#7]
Hi,

we try to move from Bower to npm and ngSilent is not registered in npm registry. Would you be willing to publish it at npmjs.com? Publishing a package should be quite straightforward: https://gist.github.com/coolaj86/1318304

Have a nice day,
Martin

**Comment by garakh** [comment]
Here is it https://www.npmjs.com/package/ngsilent

**Comment by MartyIX** [comment]
Thanks!
